config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  resources :events

  resources :logs do
    collection do
      get :changelog
    end
  end

  root "events#index"
end

app/views/layouts/_footer.html.erb
<div class="h-72 bg-slate-700 text-slate-400 font-extralight">
  <div class="container mx-auto py-12 px-5">
    Lunchtime Looser's @ <%= Time.now.strftime("%B %Y") %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="fixed top-0 <%= get_header_classes(controller) %> shadow z-50 w-full">
  <nav class="container mx-auto flex items-center justify-between pl-6 pr-0 py-3 text-slate-400">
    <a href="/" class="text-xl font-extralight text-yellow-300 flex flex-row gap-2">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 346 266" class="w-8">
        <g>
          <path d="M23,83c0-22.09139,17.90861-40,40-40h220c22.09139,0,40,17.90861,40,40v120c0,22.09139-17.90861,40-40,40h-220c-22.09139,0-40-17.90861-40-40v-120Z" fill="#6db1ff" stroke="#1071e5" stroke-width="6"/>
          <path d="M43,82c0-10.49341,8.50659-19,19-19h222c10.49341,0,19,8.50659,19,19v122c0,10.49341-8.50659,19-19,19h-222c-10.49341,0-19-8.50659-19-19v-122Z" fill="#cfe4ff" stroke="#1071e5" stroke-width="6"/>
          <path d="M83,33c0-5.522847,4.477153-10,10-10s10,4.477153,10,10v40c0,5.522847-4.477153,10-10,10s-10-4.477153-10-10v-40Zm160,0c0-5.522847,4.477153-10,10-10s10,4.477153,10,10v40c0,5.522847-4.477153,10-10,10s-10-4.477153-10-10v-40Z" fill="#6db1ff" stroke="#1071e5" stroke-width="6"/>
          <path d="M63,113c0-5.522847,4.477153-10,10-10h140c5.522847,0,10,4.477153,10,10s-4.477153,10-10,10h-140c-5.522847,0-10-4.477153-10-10Zm0,40c0-5.522847,4.477153-10,10-10h140c5.522847,0,10,4.477153,10,10s-4.477153,10-10,10h-140c-5.522847,0-10-4.477153-10-10Zm0,40c0-5.522847,4.477153-10,10-10h200c5.522847,0,10,4.477153,10,10s-4.477153,10-10,10h-200c-5.522847,0-10-4.477153-10-10Z" fill="#1071e5" stroke="#1071e5" stroke-width="2"/>
          <path d="M163,33c0-5.522847,4.477153-10,10-10s10,4.477153,10,10v40c0,5.522847-4.477153,10-10,10s-10-4.477153-10-10v-40Z" fill="#6db1ff" stroke="#1071e5" stroke-width="6"/>
        </g>
      </svg>
      Lunchtime Looser's
    </a>
    <ul class="flex space-x-2 font-extralight">
      <li><a href="<%= events_path %>" class="hover:text-white hover:bg-slate-600 px-4 py-4">Events</a></li>
      <li><a href="<%= changelog_logs_path %>" class="hover:text-white hover:bg-slate-600 px-4 py-4">Changelog</a></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Example" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png?v=2">

    <%# Includes all stylesheet files in app/views/stylesheets %>

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="relative">
    <%= render :partial => "layouts/header" %>
    <main>
      <%= yield %>
    </main>
    <%= render :partial => "layouts/footer" %>
  </body>
</html>